Loading in data

In [ ]:
import numpy as np, pandas as pd
import matplotlib.pyplot as plt

test = pd.read_csv("/content/test.csv")
print("Test shape:", test.shape )

train = pd.read_csv("/content/train.csv")
print("Train shape:",train.shape)
train.head()

Test shape: (3, 58)
Train shape: (28800, 60)

,ID,dri_score,psych_disturb,cyto_score,diabetes,hla_match_c_high,hla_high_res_8,tbi_status,arrhythmia,hla_low_res_6,...,tce_div_match,donor_related,melphalan_dose,hla_low_res_8,cardiac,hla_match_drb1_high,pulm_moderate,hla_low_res_10,efs,efs_time
0,0,N/A - non-malignant indication,No,NaN,No,NaN,NaN,No TBI,No,6.0,...,NaN,Unrelated,"N/A, Mel not given",8.0,No,2.0,No,10.0,0.0,42.356
1,1,Intermediate,No,Intermediate,No,2.0,8.0,"TBI +- Other, >cGy",No,6.0,...,Permissive mismatched,Related,"N/A, Mel not given",8.0,No,2.0,Yes,10.0,1.0,4.672
2,2,N/A - non-malignant indication,No,NaN,No,2.0,8.0,No TBI,No,6.0,...,Permissive mismatched,Related,"N/A, Mel not given",8.0,No,2.0,No,10.0,0.0,19.793
3,3,High,No,Intermediate,No,2.0,8.0,No TBI,No,6.0,...,Permissive mismatched,Unrelated,"N/A, Mel not given",8.0,No,2.0,No,10.0,0.0,102.349
4,4,High,No,NaN,No,2.0,8.0,No TBI,No,6.0,...,Permissive mismatched,Related,MEL,8.0,No,2.0,No,10.0,0.0,16.223

Handling features

In [ ]:
remove = ["ID"]
features = [c for c in train.columns if not c in remove]
print(f"There are {len(features)} FEATURES: {features}")

There are 59 FEATURES: ['dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'hla_match_c_high', 'hla_high_res_8', 'tbi_status', 'arrhythmia', 'hla_low_res_6', 'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe', 'prim_disease_hct', 'hla_high_res_6', 'cmv_status', 'hla_high_res_10', 'hla_match_dqb1_high', 'tce_imm_match', 'hla_nmdp_6', 'hla_match_c_low', 'rituximab', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'prod_type', 'cyto_score_detail', 'conditioning_intensity', 'ethnicity', 'year_hct', 'obesity', 'mrd_hct', 'in_vivo_tcd', 'tce_match', 'hla_match_a_high', 'hepatic_severe', 'donor_age', 'prior_tumor', 'hla_match_b_low', 'peptic_ulcer', 'age_at_hct', 'hla_match_a_low', 'gvhd_proph', 'rheum_issue', 'sex_match', 'hla_match_b_high', 'race_group', 'comorbidity_score', 'karnofsky_score', 'hepatic_mild', 'tce_div_match', 'donor_related', 'melphalan_dose', 'hla_low_res_8', 'cardiac', 'hla_match_drb1_high', 'pulm_moderate', 'hla_low_res_10', 'efs', 'efs_time']

In [ ]:
#divide 57 features into 4 groups
featuresA = features[:15]
featuresB = features[15:30]
featuresC = features[30:45]
featuresD = features[45:]
print(f"There are {len(featuresA)} FEATURES: {featuresA}")
print(f"There are {len(featuresB)} FEATURES: {featuresB}")
print(f"There are {len(featuresC)} FEATURES: {featuresC}")
print(f"There are {len(featuresD)} FEATURES: {featuresD}")

There are 15 FEATURES: ['dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'hla_match_c_high', 'hla_high_res_8', 'tbi_status', 'arrhythmia', 'hla_low_res_6', 'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe', 'prim_disease_hct', 'hla_high_res_6']
There are 15 FEATURES: ['cmv_status', 'hla_high_res_10', 'hla_match_dqb1_high', 'tce_imm_match', 'hla_nmdp_6', 'hla_match_c_low', 'rituximab', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'prod_type', 'cyto_score_detail', 'conditioning_intensity', 'ethnicity', 'year_hct', 'obesity']
There are 15 FEATURES: ['mrd_hct', 'in_vivo_tcd', 'tce_match', 'hla_match_a_high', 'hepatic_severe', 'donor_age', 'prior_tumor', 'hla_match_b_low', 'peptic_ulcer', 'age_at_hct', 'hla_match_a_low', 'gvhd_proph', 'rheum_issue', 'sex_match', 'hla_match_b_high']
There are 14 FEATURES: ['race_group', 'comorbidity_score', 'karnofsky_score', 'hepatic_mild', 'tce_div_match', 'donor_related', 'melphalan_dose', 'hla_low_res_8', 'cardiac', 'hla_match_drb1_high', 'pulm_moderate', 'hla_low_res_10', 'efs', 'efs_time']

In [ ]:
catFeaturesB = []
for c in featuresB:
  if train[c].dtype == "object":
    catFeaturesB.append(c)
print(f"There are {len(catFeaturesB)} CATEGORICAL FEATURES: {catFeaturesB}")

numFeaturesB = [c for c in featuresB if not c in catFeaturesB]
print(f"There are {len(numFeaturesB)} NUMERICAL FEATURES: {numFeaturesB}")

There are 8 CATEGORICAL FEATURES: ['cmv_status', 'tce_imm_match', 'rituximab', 'prod_type', 'cyto_score_detail', 'conditioning_intensity', 'ethnicity', 'obesity']
There are 7 NUMERICAL FEATURES: ['hla_high_res_10', 'hla_match_dqb1_high', 'hla_nmdp_6', 'hla_match_c_low', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'year_hct']

**NULL Val INTERPRETATION IN EACH FEATURE B**

In [ ]:
for c in catFeaturesB:
  print(train[c].value_counts(dropna=False))

cmv_status
+/+    13596
-/+     7081
+/-     4048
-/-     3441
NaN      634
Name: count, dtype: int64
tce_imm_match
P/P    13114
NaN    11133
G/G     2522
H/H     1084
G/B      544
H/B      229
P/H       83
P/B       66
P/G       25
Name: count, dtype: int64
rituximab
No     26033
NaN     2148
Yes      619
Name: count, dtype: int64
prod_type
PB    20381
BM     8419
Name: count, dtype: int64
cyto_score_detail
NaN             11923
Intermediate    11158
Poor             3323
Favorable        1208
TBD              1043
Not tested        145
Name: count, dtype: int64
conditioning_intensity
MAC                              12288
RIC                               7722
NaN                               4789
NMA                               3479
TBD                                373
No drugs reported                   87
N/A, F(pre-TED) not submitted       62
Name: count, dtype: int64
ethnicity
Not Hispanic or Latino      24482
Hispanic or Latino           3347
NaN                           587
Non-resident of the U.S.      384
Name: count, dtype: int64
obesity
No          25144
Yes          1779
NaN          1760
Not done      117
Name: count, dtype: int64

In [ ]:
#correlation of missing values with efs
for c in catFeaturesB:
  missing_c = train[c].isnull()
  missing_impact = train.groupby("efs")[c].apply(lambda x: x.isnull().sum())
  print(missing_impact)

efs
0.0    345
1.0    289
Name: cmv_status, dtype: int64
efs
0.0    5169
1.0    5964
Name: tce_imm_match, dtype: int64
efs
0.0    1000
1.0    1148
Name: rituximab, dtype: int64
efs
0.0    0
1.0    0
Name: prod_type, dtype: int64
efs
0.0    6913
1.0    5010
Name: cyto_score_detail, dtype: int64
efs
0.0    3773
1.0    1016
Name: conditioning_intensity, dtype: int64
efs
0.0    281
1.0    306
Name: ethnicity, dtype: int64
efs
0.0    800
1.0    960
Name: obesity, dtype: int64

**Handling NON-Signficant columns**

tce_imm_match,  rituximab,  prod_type,  ethnicity,  obesity

In [ ]:
#filling in null values appropriately
train["tce_imm_match"] = train["tce_imm_match"].fillna("Missing")
train["ethnicity"] = train["ethnicity"].fillna("Missing")
train["obesity"] = train["obesity"].fillna("Not done")

#using mode frequency
train["rituximab"] = train["rituximab"].fillna(train["rituximab"].mode()[0])

In [ ]:
#Encoding Categorical Features

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
#one hot encoding
train = pd.get_dummies(train, columns=["tce_imm_match", "ethnicity"], dtype=int)
train = pd.get_dummies(train, columns=["prod_type"], dtype=int)
train = pd.get_dummies(train, columns=["obesity"], dtype=int)

#Binary encoding
train["rituximab"] = train["rituximab"].map({"Yes": 1, "No": 0})

In [ ]:
  #CheckPoint
columns_to_check = ["tce_imm_match", "rituximab", "prod_type", "ethnicity", "obesity"]

for col in columns_to_check:
    encoded_cols = [c for c in train.columns if col in c]  # Find all one-hot encoded variants
    print(f"\n--- Checking: {col} ---")
    print(train[encoded_cols].head())  # Print first 5 rows of one-hot encoded columns
    print(f"Sum of 'Missing' for {col}: {train[[c for c in encoded_cols if 'Missing' in c]].sum().sum()}")  # Count missing values

--- Checking: tce_imm_match ---
   tce_imm_match_G/B  tce_imm_match_G/G  tce_imm_match_H/B  tce_imm_match_H/H  \
0                  0                  0                  0                  0
1                  0                  0                  0                  0
2                  0                  0                  0                  0
3                  0                  0                  0                  0
4                  0                  0                  0                  0

   tce_imm_match_Missing  tce_imm_match_P/B  tce_imm_match_P/G  \
0                      1                  0                  0
1                      0                  0                  0
2                      0                  0                  0
3                      0                  0                  0
4                      1                  0                  0

   tce_imm_match_P/H  tce_imm_match_P/P
0                  0                  0
1                  0                  1
2                  0                  1
3                  0                  1
4                  0                  0
Sum of 'Missing' for tce_imm_match: 11133

--- Checking: rituximab ---
   rituximab
0          0
1          0
2          0
3          0
4          0
Sum of 'Missing' for rituximab: 0.0

--- Checking: prod_type ---
   prod_type_BM  prod_type_PB
0             1             0
1             0             1
2             1             0
3             1             0
4             0             1
Sum of 'Missing' for prod_type: 0.0

--- Checking: ethnicity ---
   ethnicity_Hispanic or Latino  ethnicity_Missing  \
0                             0                  0
1                             0                  0
2                             0                  0
3                             0                  0
4                             1                  0

   ethnicity_Non-resident of the U.S.  ethnicity_Not Hispanic or Latino
0                                   0                                 1
1                                   0                                 1
2                                   0                                 1
3                                   0                                 1
4                                   0                                 0
Sum of 'Missing' for ethnicity: 587

--- Checking: obesity ---
   obesity_No  obesity_Not done  obesity_Yes
0           1                 0            0
1           1                 0            0
2           1                 0            0
3           1                 0            0
4           1                 0            0
Sum of 'Missing' for obesity: 0.0

**Handling Significant columns**

cmv_status, conditioning_intensity, cyto_score_detail

 treating missing values as a separate category can help capture any unique characteristics of those patients. This approach acknowledges that missing data might indicate a different treatment path or patient experience, which could be relevant to understanding disparities

In [ ]:
train["cmv_status"]= train["cmv_status"].fillna("Missing")
train["conditioning_intensity"]= train["conditioning_intensity"].fillna("Missing")
train["cyto_score_detail"]= train["cyto_score_detail"].fillna("Missing")

In [ ]:
#Ordinal Encoding cmv_status:

cmv_mapping = {
    "-/+": 3,      #Highest risk
    "+/-": 2,
    "-/-": 1,
    "+/+": 0,      #Lowest risk
    "Missing": -1  #category for missing
}

train["cmv_status"] = train["cmv_status"].map(cmv_mapping)

In [ ]:
cytoscore_mapping = {
    'Poor': 4,                              # Highest risk
    'TBD': 3,
    'Not tested': 2,
    'Intermediate': 1,
    'Favorable': 0,                         # Lowest risk
    'Missing': -1                           # Category for missing
}
train["cyto_score_detail"] = train["cyto_score_detail"].map(cytoscore_mapping)

In [ ]:
conditioning_mapping = {
    'MAC': 5,                              # Lowest intensity
    'RIC': 4,
    'NMA': 3,
    'TBD': 2,
    'No drugs reported': 1,
    'N/A, F(pre-TED) not submitted': 0,    #Highest intesity
    'Missing': -1                          # Category for missing
}
train["conditioning_intensity"] = train["conditioning_intensity"].map(conditioning_mapping)

In [ ]:
      #Check Point:
original_unique_values = train['cyto_score_detail'].unique()
print("Original unique values in cyto_score_detail:", original_unique_values)

original_unique_values = train['cmv_status'].unique()
print("Original unique values in cmv_status:", original_unique_values)

original_unique_values = train['conditioning_intensity'].unique()
print("Original unique values in conditioning_intensity:", original_unique_values)

Original unique values in cyto_score_detail: [-1  1  3  4  0  2]
Original unique values in cmv_status: [ 0  3  1 -1  2]
Original unique values in conditioning_intensity: [-1  5  4  3  2  1  0]

In [ ]:
# make a copy of train with just the encoded data
cols_to_add = ['cmv_status','cyto_score_detail','conditioning_intensity','rituximab','tce_imm_match_G/B', 'tce_imm_match_G/G', 'tce_imm_match_H/B', 'tce_imm_match_H/H', 'tce_imm_match_Missing', 'tce_imm_match_P/B', 'tce_imm_match_P/G', 'tce_imm_match_P/H', 'tce_imm_match_P/P', 'ethnicity_Hispanic or Latino', 'ethnicity_Missing', 'ethnicity_Non-resident of the U.S.', 'ethnicity_Not Hispanic or Latino', 'prod_type_BM', 'prod_type_PB', 'obesity_No', 'obesity_Not done', 'obesity_Yes']
train1 = train[cols_to_add].copy()
train1.head()

,cmv_status,cyto_score_detail,conditioning_intensity,rituximab,tce_imm_match_G/B,tce_imm_match_G/G,tce_imm_match_H/B,tce_imm_match_H/H,tce_imm_match_Missing,tce_imm_match_P/B,...,tce_imm_match_P/P,ethnicity_Hispanic or Latino,ethnicity_Missing,ethnicity_Non-resident of the U.S.,ethnicity_Not Hispanic or Latino,prod_type_BM,prod_type_PB,obesity_No,obesity_Not done,obesity_Yes
0,0,-1,-1,0,0,0,0,0,1,0,...,0,0,0,0,1,1,0,1,0,0
1,0,1,5,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,1,0,0
2,0,-1,-1,0,0,0,0,0,0,0,...,1,0,0,0,1,1,0,1,0,0
3,0,1,5,0,0,0,0,0,0,0,...,1,0,0,0,1,1,0,1,0,0
4,0,-1,5,0,0,0,0,0,1,0,...,0,1,0,0,0,0,1,1,0,0

In [ ]:
train.shape

(28800, 74)

**Handling Numerical Features**

In [ ]:
numFeaturesB = [c for c in featuresB if not c in catFeaturesB]
print(f"There are {len(numFeaturesB)} NUMERICAL FEATURES: {numFeaturesB}")

There are 7 NUMERICAL FEATURES: ['hla_high_res_10', 'hla_match_dqb1_high', 'hla_nmdp_6', 'hla_match_c_low', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'year_hct']

In [ ]:
hla_features = ['hla_high_res_10', 'hla_match_dqb1_high', 'hla_match_c_low', 'hla_match_dqb1_low']

for feature in hla_features:
    median_value = train[feature].median()
    train[feature] = train[feature].fillna(median_value)

In [ ]:
nonsig_hla_features = ['hla_match_drb1_low', 'hla_nmdp_6']

for feature in nonsig_hla_features:
  median_value = train[feature].median()
  train[feature] = train[feature].fillna(median_value)

**Table containing just FeaturesB with encoded data**

In [ ]:
featuresB_updated = ['hla_high_res_10', 'hla_match_dqb1_high', 'hla_nmdp_6', 'hla_match_c_low', 'hla_match_drb1_low', 'hla_match_dqb1_low', 'year_hct','cmv_status','cyto_score_detail','conditioning_intensity','rituximab','tce_imm_match_G/B', 'tce_imm_match_G/G', 'tce_imm_match_H/B', 'tce_imm_match_H/H', 'tce_imm_match_Missing', 'tce_imm_match_P/B', 'tce_imm_match_P/G', 'tce_imm_match_P/H', 'tce_imm_match_P/P', 'ethnicity_Hispanic or Latino', 'ethnicity_Missing', 'ethnicity_Non-resident of the U.S.', 'ethnicity_Not Hispanic or Latino', 'prod_type_BM', 'prod_type_PB', 'obesity_No', 'obesity_Not done', 'obesity_Yes']
train1 = train[featuresB_updated].copy()
print(train1.head())
train1.shape

#save as csv file
train1.to_csv('featuresB_encoded.csv', index=False)

   hla_high_res_10  hla_match_dqb1_high  hla_nmdp_6  hla_match_c_low  \
0             10.0                  2.0         6.0              2.0
1             10.0                  2.0         6.0              2.0
2             10.0                  2.0         6.0              2.0
3             10.0                  2.0         6.0              2.0
4             10.0                  2.0         5.0              2.0

   hla_match_drb1_low  hla_match_dqb1_low  year_hct  cmv_status  \
0                 2.0                 2.0      2016           0
1                 2.0                 2.0      2008           0
2                 2.0                 2.0      2019           0
3                 2.0                 2.0      2009           0
4                 2.0                 2.0      2018           0

   cyto_score_detail  conditioning_intensity  ...  tce_imm_match_P/P  \
0                 -1                      -1  ...                  0
1                  1                       5  ...                  1
2                 -1                      -1  ...                  1
3                  1                       5  ...                  1
4                 -1                       5  ...                  0

   ethnicity_Hispanic or Latino  ethnicity_Missing  \
0                             0                  0
1                             0                  0
2                             0                  0
3                             0                  0
4                             1                  0

   ethnicity_Non-resident of the U.S.  ethnicity_Not Hispanic or Latino  \
0                                   0                                 1
1                                   0                                 1
2                                   0                                 1
3                                   0                                 1
4                                   0                                 0

   prod_type_BM  prod_type_PB  obesity_No  obesity_Not done  obesity_Yes
0             1             0           1                 0            0
1             0             1           1                 0            0
2             1             0           1                 0            0
3             1             0           1                 0            0
4             0             1           1                 0            0

[5 rows x 29 columns]